name: deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
        
      - run: npm install
      - run: npm run lint

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
      
      - name: Setup SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            sudo apt update
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            nvm install 21
            nvm use 21

            mkdir -p test
            cd test

            ls -a

            if [ -d "cicd-do-sample" ]; then
              rm -rf cicd-do-sample
            fi

            git clone git@github.com:ricpanoptik/cicd-do-sample.git
            cd cicd-do-sample
            ls -a

            npm install
            pkill -f "npm run dev"
            nohup npm run dev > output.log 2>&1 &
            echo "Deployment complete!"
      
      - name: Install Nginx
        run: sudo apt update && sudo apt install -y nginx
      
      - name: Configure Nginx
        run: |
          echo "server {
              listen 80;
              server_name yourdomain.com;
              location / {
                  proxy_pass http://localhost:5173;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade \$http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host \$host;
                  proxy_cache_bypass \$http_upgrade;
              }
          }" | sudo tee /etc/nginx/sites-available/yourdomain.com
          sudo ln -s /etc/nginx/sites-available/yourdomain.com /etc/nginx/sites-enabled/
          sudo service nginx restart