name: deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
        
      - run: npm install
      - run: npm run lint

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
      
      - name: Setup SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            sudo apt update
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            nvm install 21
            nvm use 21

            mkdir -p test
            cd test

            ls -a

            if [ -d "cicd-do-sample" ]; then
              rm -rf cicd-do-sample
            fi

            git clone git@github.com:ricpanoptik/cicd-do-sample.git
            cd cicd-do-sample
            ls -a

            npm install
            npm run build
            cd ../../
            echo "Build complete!"
      
      - name: Copy files
        run: |
          pwd
          ls -a
          sudo rsync -av test/cicd-do-sample/dist/ /var/www/cicd-testing/html/
      
      - name: Configure Nginx
        run: |
          echo "server {
              listen 80;
              server_name cicd-testing.com www.cicd-testing.com;
              location / {
                root /var/www/cicd-testing/html;
                try_files \$uri /index.html;
              }
          }" | sudo tee /etc/nginx/sites-available/cicd-testing.com
          sudo ln -s /etc/nginx/sites-available/cicd-testing.com /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo service nginx restart
